Ecommerce_Project/urls.py
from django.contrib import admin
from django.urls import path, include


# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home_App.urls')),
    path('account/', include('Login_App.urls')),
    path('shop/', include('Order_App.urls')),
    path('payment/', include('Payment_App.urls')),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home_App/urls.py
from django.urls import path
from .views.product_view import Home, ProductDetail

app_name = 'Home_App'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('product/<pk>/', ProductDetail.as_view(), name='product_detail'),
]

Order_App/urls.py
from django.urls import path
from Order_App import views

app_name = 'Order_App'

urlpatterns = [
        path('add/<pk>/', views.add_to_cart, name="add"),
        path('remove/<pk>/', views.remove_from_cart, name="remove"),
        path('cart/', views.cart_view, name="cart"),
        path('increase/<pk>/', views.increase_cart, name="increase"),
        path('decrease/<pk>/', views.decrease_cart, name="decrease"),

]

Home_App/models/product_model.py
from django.db import models

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"

class Product(models.Model):
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created',]

Home_App/views/product_view.py
from django.shortcuts import render

# Import views
from django.views.generic import ListView, DetailView

# Models
from Home_App.models.product_model import Product

# Mixin
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class Home(ListView):
    model = Product
    template_name = 'home.html'

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'shop_templates/product_detail.html'

Home_App/templates/shop_templates/product_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
  <div class="card">
    <div class="row">
      <aside class="col-sm-5 border-right">
        <article class="gallery-wrap">
          <div class="img-big-wrap">
            <div>
              <a href="#"><img src="/media/{{object.mainimage}}" style="width:450px ; height: 500px"></a>
            </div>
          </div>
        </article>
      </aside>
      <aside class="col-sm-7">
        <article class="card-body p-5">
          <h3 class="title mp-3">{{object.name}}</h3>
          <p class="price-detail-wrap">
            <span class="price h3 text-info">
              <span class="currency">BDT &#2547;</span><span class="num">{{object.price}}</span>
            </span>
          </p>
          <dl class="item-property">
            <dt>Description</dt>
            <dd>
              <p>{{object.detail_text|linebreaks}}</p>
            </dd>
          </dl>
          <a href="{% url 'Order_App:add' pk=object.pk %}" class="btn btn-lg btn-outline-info text-uppercase"> <i class="fas fa-shopping-cart"></i> Add to Cart</a>
        </article>
      </aside>
    </div>
  </div>
</div>
{% endblock %}