Ecommerce_Project/urls.py
from django.contrib import admin
from django.urls import path, include


# To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home_App.urls')),
    path('account/', include('Login_App.urls')),
    path('shop/', include('Order_App.urls')),
    path('payment/', include('Payment_App.urls')),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home_App/urls.py
from django.urls import path
from .views.product_view import Home, ProductDetail

app_name = 'Home_App'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('product/<pk>/', ProductDetail.as_view(), name='product_detail'),
]

Login_App/urls.py
from django.conf.urls import url
from django.urls import path
from .views.signup_view import Sign_up
from .views.profile_view import User_profile, profile_details
from .views.login_view import Login_user, logout_user


app_name = "Login_App"

urlpatterns = [
    path('signup/', Sign_up.as_view(), name = 'signup'),
    path('login/', Login_user.as_view(), name = 'login'),
    path('logout/', logout_user, name='logout'),
    path('profile/', User_profile.as_view(), name = 'profile'),
    path('profile_details/', profile_details, name = 'profile_details'),


]

Order_App/urls.py
from django.urls import path
from Order_App import views

app_name = 'Order_App'

urlpatterns = [
        path('add/<pk>/', views.add_to_cart, name="add"),
        path('remove/<pk>/', views.remove_from_cart, name="remove"),
        path('cart/', views.cart_view, name="cart"),
        path('increase/<pk>/', views.increase_cart, name="increase"),
        path('decrease/<pk>/', views.decrease_cart, name="decrease"),

]

Payment_App/urls.py
from django.urls import path
from Payment_App import views

app_name = "Payment_App"

urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('pay/', views.payment, name="payment"),
    path('status/', views.complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name="purchase"),
    path('orders/', views.order_view, name="orders"),
]

Home_App/models/product_model.py
from django.db import models

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"

class Product(models.Model):
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created',]

Home_App/views/product_view.py
from django.shortcuts import render

# Import views
from django.views.generic import ListView, DetailView

# Models
from Home_App.models.product_model import Product

# Mixin
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class Home(ListView):
    model = Product
    template_name = 'home.html'

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'shop_templates/product_detail.html'

Home_App/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>{% block title_block %} CROWN MALABIS | Clothing (brand) {% endblock %}</title>
  <style>
  .card {
    height: 350px;
  }

  .card-product:after {
    content: "";
    display: table;
    clear: both;
    visibility: hidden;
  }
  .card-product .price-new, .card-product .price {
    margin-right: 5px;
  }

  .card-product .price-old {
    color: #999;
  }

  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;
    overflow: hidden;
    position: relative;
    height: 220px;
    text-align: center;
  }

  .card-product .img-wrap img {
    max-height: 100%;
    max-width: 100%;
    object-fit: contain;
  }

  .card-product .info-wrap {
    overflow: hidden;
    padding: 15px;
    border-top: 1px solid #eee;
  }

  .card-product .action-wrap {
    padding-top: 4px;
    margin-top: 4px;
  }

  .card-product .bottom-wrap {
    padding: 15px;
    border-top: 1px solid #eee;
  }

  .card-product .title {
    margin-top: 0px;
  }
</style>

</head>
<body>
  {% include 'navbar.html' %}
  <div class="container">
    <div class="messages container mt-2">
      {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    {% block body_block %} {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

Home_App/templates/home.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
  <h2 class="my-5" align="center" >Featured Products</h2>
  <div class="row">
    {% for product in object_list %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
        </div>
        <figcaption class="info-wrap">
          <h6 class="title text-uppercase "><a class="text-success" href="{% url 'Home_App:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
                <span class="price-new">{{product.preview_text}}</span><br><br>
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
                <br>
                <br>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

Home_App/templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'Home_App:home' %}">CROWN MALABIS</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'Order_App:cart' %}" class="nav-link">
              <i class="fa fa-shopping-cart"></i> Cart
              <span class="badge badge-light">{{ request.user | cart_total }}</span>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i> {{request.user.profile.username}}</a>
          <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
            <a class="dropdown-item" href="{% url 'Login_App:profile_details' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'Payment_App:orders' %}">Orders</a>
            <a class="dropdown-item" href="{% url 'Login_App:profile' %}">Edit Profile</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'Login_App:logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'Login_App:login' %}" class="btn btn-outline-secondary">Login</a>
          <a href="{% url 'Login_App:signup' %}" class="btn btn-secondary">SignUp</a>
        </li>

        {% endif %}
      </ul>
    </div>
  </div>
</nav>